{["src/weather_sup",
  "src/weather_app",
  "src/wx",
  "src/wx_sup",
  "src/httpc",
  "src/http_master",
  "src/http_sup",
  "src/envcan_api",
  "lib/erlang_twitter/twitter_client",
  "src/twitter_status"],
  
 [{outdir, "ebin"},
  {i, "include"},
  {i, "/usr/local/lib/erlang/lib/xmerl-1.1.4/include/"},
  {i, "/usr/lib/erlang/lib/xmerl-1.1.4/include/"},
  {i, "lib/erlang_twitter"}]}.